services:
- type: web
  name: v6
  runtime: node
  branch: main
  region: oregon
  plan: free
  repo: https://github.com/Glitch-Network/v6
  buildCommand: yarn
  startCommand: npm start
  rootDir: ./
version: "6"